### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by leafsfan525** [l3uddz/ss-tvirl#5] opened 2017-10-05 23:44 UTC
Everything seemed to be working fine until when I started getting the message: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Any idea what might be causing this?

**Comment by leafsfan525** [comment] 2017-10-05 23:51
This only seem to occur when trying to access http://SERVER_HOST:PORT/SERVER_PATH/playlist.m3u8

If I add ?channel=## then it works.

**Comment by l3uddz** [comment] 2017-10-06 11:14
Thanks for this report. Please update it and let me know if that solves your problem. I'm hoping the issue is related to the error it was having building the playlist (smoothstreams have removed channels 151-155, which I did not expect / account for).

Let me know if this solves your problem, if it does, please close the issue. THanks!

**Comment by leafsfan525** [comment] 2017-10-06 12:19
That worked, thank you!

**Closed** 2017-10-06 12:20 UTC
